a = house ful bhouse fult until next week","honest",2,3,4,4,4,2,2,4,5,6)
print(a)
print(type(a))
print(a.index("honest"))
print(a.count(4))
print(a.count(2))
print(a.__sizeof__())
print(len(a))
b = str(a)
print(str(b))
print(type(b))
print(list(a))
print(set(a))
mpreddy = [1,2,3,4,5]
print(mpreddy)