open = open("file_handaling","r+")
# prin = open.read(67)
# print(prin)
# # prin = open.read(67)
# print(prin)
# print(type(prin))
# readline = open.readline(100)
# print(readline)
# readline = open.readline(100)
# print(readline)
# print(type(readline))
readlines = open.readlines(10)
print(readlines)
print(type(readlines))
#print(open.write(" , my goal is a python job"))
#print(open.seek(1))
jh = open("append","w")
gf = open.writelines(jh)
print(gf)