a = "goal,aim"
print(a)
print(a.split())
print(a.split(","))
print(a.index("aim"))
print(a.index("m"))
print(a.upper())
print(a.encode())
b = a.encode()
print(b)
print(b.decode())
c = b'goal,aim'
print(c)
print(type(c))
print(a.find("aim"))
print(a.find("j"))
print(a.find("k"))
print(a.join("confidence"))
print(" ".join("error"))
search = "+,%,#"
assembly = ["e","b",]
print(search.join(assembly))
court = ("4","6","565")
print(search.join(court))
print(a)
print(a.replace("aim","youth"))
print(a.count("aim"))
print(a.capitalize())
print(a.casefold())
print(a.endswith("koll"))
print(a.endswith("aim"))
print(a.endswith("goal"))
print(a.endswith("m"))
print(f"reddy{a}:")
print("fort {} :".format("dog"))
print(f"soul {'a'}")
print(type(a))
print(list(a))
print(a)
print(list(a))
print(len(a))
print(set(a))
print(tuple(a))
print(a.lower())
print(a.upper())
print(a.capitalize())
print(a.casefold())
print(a)
