a = "padmareddy"
print(a)
print(type(a))
print(a.index('r'))
print(a.count('d'))
print(a.encode())
print(a.join('ramakrishnareddy'))

print('jel'.join(a))
print(a.replace('d','aarika'))
print(a.find('a'))
print(a.isupper())
print(a.upper())
print(a.lower())
print(a.isdecimal())
print(a.capitalize())
print(a.isdigit())
print(list(a))
print(a)
print(type(a))
print(tuple(a))
print(type(a))
print("join names {} {} :".format('redddy','reddu'))
print(a.__sizeof__())
for pythonjob in a:
    print(pythonjob)
print(a)
while a:
    print(a)
    break
toy = ['pathapreddy','padmarddy','venkataravana','ramakrishna']
print(toy)
print(type(toy))
print(toy.pop())
print(toy)
print(toy.copy())
print(toy.index('venkataravana'))
(toy.reverse())
print(toy)
(toy.insert(1,'malapati'))
print(toy)
(toy.insert(3,'mulamreddy ramakrishna reddy'))
print(toy)
def d(toy):
    print(d)
dox = [3,323,32]
d(dox)
print(dox)
(toy.append("malapati lingareddy"))
print(toy)
toy.sort()
print(toy)
(toy.extend('satisfaction'))
print(toy)
print(toy.__sizeof__())
print(tuple(toy))
print(str(toy))
print(set(toy))
print(type(toy))
for dangerzone in toy:
    print(dangerzone)
def folk(dan):
    dan = ['python']
    print(folk)
    return folk
folk = [32,32,232,3]
print(folk)
server = ('ganga','jail','rough','krane',3,45,5,5,5,6)
print(server)
print(type(server))
print(server.count(5))
print(server.__str__())
print(list(server))
print(set(server))
#print(server.__reversed__())
print(server.__sizeof__())
file = {"python":"automachine","solid":"dry","marks":"48","pysics":'56','chemistry':'69'}
print(file)
print(type(file))
print(file.values())
print(file.keys())
print(file.items())
print(file.fromkeys('r'))
print(file.__len__())
print(len(file))
print(len(toy))
for dox in file:
    print(dox)
    for got in dox:
        print(got)
while got:
    print(got)
    break
prathap = {'tolk','high','bottle'}
print(prathap)
print(type(prathap))

print(prathap.__len__())
(prathap.update('bottle','house'))
print(prathap)
(prathap.remove('tolk'))
print(prathap)
print(toy.pop())
print(toy)
print(type(prathap))
print(type(server))
print(a)
print(type(a))
print(toy.index("pathapreddy"))
print(len(toy))
print(prathap)
(prathap.remove('bottle'))
print(prathap)
print(prathap.__sizeof__())
print(str(prathap))
print(prathap)
print(type(prathap))
(prathap.update("jol",'high'))
print(prathap)
