a = 'prathapredddy'
print(a)
print(type(a))
b = "prathapreddy"
print(b)
print(type(b))
#print(b.index("m"))
print(b.count("a"))
print(b.find("y"))
print(b.join("prathap"))
print("pra".join(b))
print(b.upper())
print(b)
print(len(b))
print(b.capitalize())
print(list(b))
print(set(b))
print(b)


pra = (2,323,32,23,23,34,434,'prathap','man')
print(pra)
print(type(pra))
print(pra.count(23))
print(pra.index('man'))
print(pra.__sizeof__())
print(str(pra))
print(pra)
print(list(pra))
print(set(pra))
print(pra.__hash__())
print(pra.count('prathap'))
print(type(pra))
man = ['rough','manprathap ','prathapreddy','venkataravana']
print(man)
print(type(man))
print(set(man))
print(str(man))
print(man.count('rough'))
print(type(man))
(man.sort())
print(man)
(man.insert(2,'prathaman'))
print(man)
print(man.pop())
print(man)
(man.append('jokey'))
print(man)
manprathaoreddy = man.copy()
print(manprathaoreddy)
print(manprathaoreddy)
(man.sort())
print(man)
(manprathaoreddy.reverse())
print(manprathaoreddy.__str__())
print(tuple(manprathaoreddy))
print(set(manprathaoreddy))
print(type(manprathaoreddy))
print(man.__sizeof__())
prathap = {'man':45,'hihg':158,'post':50000}
print(prathap)
print(prathap.values())
print(prathap.keys())
print(prathap.items())
(prathap.get(45))
print(prathap)
print(str(prathap))
print(tuple(prathap))
print(set(prathap))
print(prathap.popitem())
print(type(pra))
for f in pra:
    print(f)
print(pra.__len__())
print(pra.__sizeof__())

for pop in pra:
    print(pop)
print(prathap)
print(pra.__sizeof__())
print(b)
print(pra)
print(pra.count(34))
