d = 'prathapreddy'
print(d)
print(d.encode())
print(d.index('y'))
print(d.upper())
print(d.join('happy'))
print('100'.join(d))
print(d.casefold())
print(d.casefold())
print(d.swapcase())
print(d.isupper())
print(d)
print(d.isspace())
print(type(d))
print(d.replace('reddy','venakataravana'))
print(d.isdecimal())
first_name = 'prathap'
last_name = 'reddy'
print(d.format())
print('name {} {}.'.format(first_name,last_name))
print('my name is {}.'.format(first_name) )
print(d.__len__())
print(len(d))
#print(d.__doc__)
print(dir(d))
print(d.__repr__())
print(repr(d))
g = 'padma'
h = [1,2,3]
print(str(h))
print(repr(g))
print(str(g))
pythonjob = [5,23,3,1,5,6,7,8]
print(pythonjob)
print(pythonjob.index(8))
(pythonjob.sort())
print(pythonjob)
print(pythonjob.pop())
print(pythonjob)
(pythonjob.append('reddy'))
print(pythonjob)
k = (pythonjob.copy())
print(k)
print(k)
print(type(k))
(pythonjob.insert(2,23))
print(pythonjob)
(k.reverse())
print(k)

pythonjob.extend('reddy')
print(pythonjob)
#print(k.__format__())
print('my name {} {}.'.format('tollgate','colgate'))
print(k.__dir__())
print(k)
jokey = (1,3,4,5,6,'you','me','joll','kole','coal')
print(jokey)
print(type(jokey))
print(jokey.index('coal'))
print(jokey.__dir__())
print(jokey.__sizeof__())
danger = {"report":"normal",'cbp':'count low',"hetamology":"serum","white cells":"counting low"}
print(danger)
print(danger.values())
print(danger.keys())
print(danger.get('cbp'))
print(danger.items())
print(danger.__sizeof__())
print(type(danger))
print(danger.get('hetamology'))
for games in danger:
    print(games)

while danger:
    print(danger)
    break
fell = {"redd","reddt","gg","gggg"}
print(fell)
print(type(fell))
print(fell.__sizeof__())
(fell.add('venkata'))
print(fell)
