a = ['gf',2,343,343,3434,343]
print(a)
print(list(set(a)))
print(set(a))
d = (2,2,3,3)
print(d)
print(set(d))
print(tuple(set(d)))
b = {'set':'34','4566':'65656','65656':'657676'}
print(b)
print(set(b))
print(b.keys())
print(b.values())
a = [(2,4)]
f = dict(set(a))
print(f)
print(f.keys())
print(f.values())

b = {'set':'34','4566':'65656','65656':'657676'}
print(list(zip(b.keys(), b.values())))
print(b.items())
print(b.get('set'))
print(b.__len__())
print(len(b))
print(b.__dir__())

b = [1, 2, 3, 5]
c = ["a", 1, 3, 4, 5]

print(list(zip(c, b)))
a = [23,232,232,232,232,44,3,3,5,1,7]
print(a)
print(set(a))
print(type(a))
print(a)
print(set(a))
print(tuple(a))
d = ('rt','rt','jkl')
print(d)
print(set(d))
print(d)
print(type(d))
v = {1,2}
print(v)
print(type(v))
v.add(23)
print(v)
h = {45,67}
print(v.update(h))
print(v)
h.update(v)
print(h)
g = {3,4,5,65}
h = {6,65,3}
h.update(g)
print(h)
h.remove(6)
print(h)
h.discard(65)
print(h)
h.pop()
print(h)
h.clear()
print(h)
print(v)
print (max(v))

print(sum(v))
print(min(v))
y = {434,545,879}
print(y)
g = (map(v,y))
print(g)
print(v,y)
(y.discard(45))
print(y)
print(type(y))
(y.add('try'))
print(y)
print(y.pop()) # pop function remove to first element
print(y)
(y.update('house python'))
print(y)
print(set(y))
g = (y.copy())
print(g)
print(g)
print(type(g))
print(g.__dir__())
print(g.difference(y))
print(len(g))
print(g.__sizeof__())
print(g.__len__())
print(g)
#print(g.remove(545))
print(g)
(g.add('prathapreddy'))
print(g)
print(g.pop())
print(g)
print(g.pop())
print(g)
print(g.__len__())
print(b)
print(type(b))
print(str(b))
print(set(b))
print(b.insert(2,'rehaman'))
print(b)
g = 323234
while g:
    print(g)
    break
print(g.__sizeof__())
print(d)
f = (3,4.55,5)
print(f)
print(d.__add__(f))
print(d)
print(d.index('rt'))
print(d.index('jkl'))
print(f)
print(f.__len__())
print(len(f))
(f.__init__())
print(f)
